baseURL = 'https://richardschwabe.github.io'
languageCode = 'en-us'
title = 'Richard Schwabe'
theme = "freelancer"

disqusShortname = "www-richardschwabe-de"
googleAnalytics = "G-GC8SR0HG51"
pluralizeListTitles = false
enableemoji = true

[params]
  tagLine = "Software Developer - Dad - Youtuber"
  homePosts = 3
  homeProjects = 3

  aboutLeft = "I like technology and I like to share my knowledge. I mostly do Software Development, but my specilisation is Information Security."
  aboutRight = "I picked up my Youtube channel in October 2022 and love making videos about python and bot development."

[[params.social]]
  icon_pack='fa-brands'
  icon="youtube"
  url="https://www.youtube.com/@richardschwabe"

[[params.social]]
  icon_pack='fa-solid'
  icon="tree"
  url="https://www.linktr.ee/richardschwabe"

[[params.social]]
  icon_pack='fa-brands'
  icon="discord"
  url="https://discord.gg/6h3xTkrpQT"

[params.location]
  lineOne = "2215 John Daniel Drive"
  lineTwo = "Clark, MO 65243"

[params.sbform]
      token = ""


[related]
  includeNewer = true
  threshold = 80
  toLower = false
[[related.indices]]
  name = 'tags'
  weight = 100
[[related.indices]]
  name = 'date'
  weight = 10